apiVersion: v1
kind: Service
metadata:
  name: pumrporderservice
  labels:
    version: PartsUnlimitedMrp
spec:
  selector: 
    app: PartsUnlimitedMrp
    tier: OrderService
    link: PartsUnlimitedMrp
  type: ClusterIP
  sessionAffinity: None
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pumrporderdeployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: PartsUnlimitedMrp
        tier: OrderDeployment
        link: PartsUnlimitedMrp
    spec:
      containers:
      - name: partsunlimitedmrp
        image: puregistry-on.azurecr.io/puorder:latest
        ports:
        - name: http
          containerPort: 8080
      imagePullSecrets:
        - name: puregistrykey
