apiVersion: v1
kind: Service
metadata:
  name: pumrpclientservice
  labels:
    version: PartsUnlimitedMrp
spec:
  selector: 
    app: PartsUnlimitedMrp
    tier: FrontendService
    link: PartsUnlimitedMrp
  type: LoadBalancer
  sessionAffinity: None
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pumrpclientdeployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: PartsUnlimitedMrp
        tier: FrontendDeployment
        link: PartsUnlimitedMrp
    spec:
      containers:
      - name: partsunlimitedmrp
        image: puregistry-on.azurecr.io/puclient:latest
        ports:
        - name: http
          containerPort: 8080
      imagePullSecrets:
        - name: puregistrykey