apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        tier: {{ .Values.labels.tier }}
        link: {{ .Values.labels.link }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: varlog
          mountPath: /DealerApi/Dealer/EventLogs/
      - name: fluentddealer-agent
        image: gcr.io/google_containers/fluentd-gcp:1.30
        env:
        - name: FLUENTD_ARGS
          value: -c /etc/fluentd-config/fluentd.conf
        volumeMounts:
        - name: varlog
          mountPath: /DealerApi/Dealer/EventLogs/
        - name: config-volume
          mountPath: /etc/fluentd-config
        ports:
        - name: {{ .Values.service.portName }}
          containerPort: {{ .Values.service.internalPort }}
      imagePullSecrets:
      - name: {{ .Values.service.imagePullSecrets }}
      volumes:
      - name: varlog
        emptyDir: {}
      - name: config-volume
        configMap:
          name: fluentddeployment-config
