# Default values for orderservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: puregistry-on.azurecr.io/zipkin
  tag: latest
  pullPolicy: IfNotPresent
labels:
  tier: backend
  link: PartsUnlimitedMrp
service:
  name: zipkin
  type: LoadBalancer
  portName: http
  externalPort: 9411
  internalPort: 9411
  imagePullSecrets: puregistrykey
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

